### PR TITLE
no more zombie turns

### LINKED ISSUE #84: Dead pokemon can still take turns.
## Current Behavior
If a pokemon faints before taking it's turn, it will ignore the fact that it is dead, and take it's turn anyway.

**To Reproduce**
Code snippet to reproduce the problem (if applicable)

<details>
<summary>Failing test case 1</summary>

```go
func TestBattleDeadPokemonForfeitTurn(t *testing.T) {
	a1 := Agent(dumbAgent{})
	a2 := Agent(dumbAgent{})
	party1 := NewParty(&a1, 0)
	pkmn1 := GetPokemon(4)
	pkmn1.Stats = [6]uint{30, 10, 10, 10, 10, 10}
	pkmn1.CurrentHP = 1
	pound := GetMove(1)
	pkmn1.Moves[0] = &pound
	party1.AddPokemon(&pkmn1)
	party2 := NewParty(&a2, 1)
	pkmn2 := GetPokemon(7)
	pkmn2.Stats = [6]uint{30, 10, 10, 10, 10, 100}
	pkmn2.CurrentHP = 30
	pkmn2.Moves[0] = &pound
	party2.AddPokemon(&pkmn2)
	b := NewBattle()
	b.AddParty(party1, party2)
	err := b.Start()
	if err != nil {
		t.Fatal("failed to start battle")
	}

	transactions, ended := b.SimulateRound()
	if !ended {
		t.Error("Expected SimulateRound to indicate that the battle has ended, but it did not.")
	}
	if n := len(transactions); n != 3 {
		t.Errorf("Expected 3 transactions to occur, got %d", n)
	}
	logtest := []struct {
		turn Transaction
		want string
	}{
		{
			turn: transactions[0],
			want: "Squirtle used Pound on Charmander for 3 damage.",
		},
		{
			turn: transactions[1],
			want: "Charmander fainted.",
		},
		{
			turn: transactions[2],
			want: "The battle has ended.",
		},
	}
	for _, tt := range logtest {
		got := tt.turn.BattleLog()
		if got != tt.want {
			t.Errorf("Expected battle log to be %s, got %s", tt.want, got)
		}
	}
}
```
</details>

<details>
<summary>Failing test case 2</summary>

```go
func TestBattleDeadPokemonForfeitTurn2(t *testing.T) {
	a1 := Agent(dumbAgent{})
	a2 := Agent(dumbAgent{})
	party1 := NewParty(&a1, 0)
	pkmn1 := GetPokemon(4)
	pkmn3 := GetPokemon(387)
	pkmn1.Stats = [6]uint{30, 10, 10, 10, 10, 10}
	pkmn1.CurrentHP = 1
	pkmn3.Stats = [6]uint{30, 10, 10, 10, 10, 10}
	pkmn3.CurrentHP = 30
	pound := GetMove(1)
	pkmn1.Moves[0] = &pound
	pkmn3.Moves[0] = &pound
	party1.AddPokemon(&pkmn1, &pkmn3)
	party2 := NewParty(&a2, 1)
	pkmn2 := GetPokemon(7)
	pkmn2.Stats = [6]uint{30, 10, 10, 10, 10, 100}
	pkmn2.CurrentHP = 30
	pkmn2.Moves[0] = &pound
	party2.AddPokemon(&pkmn2)
	b := NewBattle()
	b.AddParty(party1, party2)
	err := b.Start()
	if err != nil {
		t.Fatal("failed to start battle")
	}

	transactions, _ := b.SimulateRound()
	if n := len(transactions); n != 3 {
		t.Errorf("Expected 3 transactions to occur, got %d", n)
	}
	logtest := []struct {
		turn Transaction
		want string
	}{
		{
			turn: transactions[0],
			want: "Squirtle used Pound on Charmander for 3 damage.",
		},
		{
			turn: transactions[1],
			want: "Charmander fainted.",
		},
		{
			turn: transactions[2],
			want: "Turtwig was sent out.",
		},
	}
	for _, tt := range logtest {
		got := tt.turn.BattleLog()
		if got != tt.want {
			t.Errorf("Expected battle log to be %s, got %s", tt.want, got)
		}
	}
}
```
</details>

## Expected Behavior
Inactive pokemon should be unable to take turns. If a pokemon is deactivated before it takes it's turn, the turn is ignored.

**Additional context**

### PR DESCRIPTION
**Pull request by dyc3**
- prevent dead pokemon from being able to take turns, fixes #84
- refactor dead pokemon tests to use gomega instead

### CODE REVIEW

File: battle.go [hunk 1]
```diff
@@ -93,11 +93,20 @@ func (b *Battle) SimulateRound() ([]Transaction, bool) {
...
 			ctx := b.getContext(party, pokemon)
 			turn := (*party.Agent).Act(ctx)
-			turns = append(turns, TurnContext{Turn: turn, Context: ctx})
+			turns = append(turns, TurnContext{
+				User: target{
+					Pokemon:   *pokemon,
+					party:     i,
+					partySlot: j,
+					Team:      party.team,
+				},
```
Comment (adapap) [inline battle.go:106]: I like the way you handled this.

**Review by adapap — APPROVED** [review]
LGTM
