### PR TITLE
fix aggressive floor divides, causing accuracy to become zero

### LINKED ISSUE #338: Battle does not end because moves keep failing
## Current Behavior
The battle described in the playground below does not end

**To Reproduce**
Code snippet to reproduce the problem (if applicable)
<details>
<summary>Playground</summary>

```go
package main

import (
	"fmt"
	"log"

	. "github.com/StevensSEC/pokemonbattlelib"
)

type smartAgent struct{}

func (smartAgent) Act(ctx *BattleContext) Turn {
	best := 0
	for i, target := range ctx.Opponents {
		if target.Pokemon.Defense() < ctx.Opponents[best].Pokemon.Defense() {
			best = i
		}
	}
	opponent := ctx.Opponents[best].Pokemon
	var strongestMove int
	var strongestDamage uint
	for i, move := range ctx.Pokemon.Moves {
		if move == nil {
			continue
		}
		damage := CalcMoveDamage(ctx.Battle.Weather, &ctx.Pokemon, opponent, move)
		if damage > strongestDamage {
			strongestDamage = damage
			strongestMove = i
		}
	}
	return FightTurn{
		Move:   strongestMove,
		Target: ctx.Opponents[best],
	}
}

func check(err error) {
	if err != nil {
		fmt.Printf("Error: %v", err)
	}
}

func main() {
	a1 := Agent(new(smartAgent))
	a2 := Agent(new(smartAgent))

	b := NewBattle()

	party0 := NewOccupiedParty(
		GeneratePokemon(362, WithLevel(50), WithMoves(383, 317, 121, 36), WithIVs([6]uint8{0x0, 0x0, 0x0, 0x0, 0x0, 0x0})),
		GeneratePokemon(388, WithLevel(52), WithMoves(10, 134, 383, 436), WithIVs([6]uint8{0x0, 0x0, 0x0, 0x0, 0x0, 0x0})),
		GeneratePokemon(432, WithLevel(50), WithMoves(356, 377, 104, 366), WithIVs([6]uint8{0x0, 0x0, 0x0, 0x0, 0x0, 0x0})),
	)
	party1 := NewOccupiedParty(
		GeneratePokemon(383, WithLevel(47), WithMoves(49, 138, 60, 123), WithIVs([6]uint8{0x0, 0x0, 0x0, 0x0, 0x0, 0x0})),
		GeneratePokemon(119, WithLevel(47), WithMoves(229, 432, 112, 134), WithIVs([6]uint8{0x0, 0x0, 0x0, 0x0, 0x0, 0x0})),
	)

	b.AddParty(party0, &a1, 0)
	b.AddParty(party1, &a2, 1)

	err := b.Start()
	if err != nil {
		log.Fatalf("couldn't start battle: %s", err)
	}

	for {
		for _, t := range b.GetTargetsRef() {
			log.Printf("%s - %d HP", t.Pokemon, t.Pokemon.CurrentHP)
		}
		transactions, ended := b.SimulateRound()
		for _, t := range transactions {
			switch tt := t.(type) {
			case DamageTransaction:
				log.Printf("%s used %s on %s for %d damage", tt.User, tt.Move, tt.Target.Pokemon, tt.Damage)
			case FaintTransaction:
				log.Printf("%s fainted", tt.Target.Pokemon)
			default:
				log.Printf("Transaction: %T - %v", t, t)
			}
		}
		if ended {
			break
		}
	}
}

```
</details>

## Expected Behavior
The battle should eventually end.

### PR DESCRIPTION
**Pull request by dyc3**
fixes #338
﻿

### CODE REVIEW

File: calc.go [hunk 1]
```diff
@@ -84,7 +84,7 @@ func CalcMoveDamage(weather Weather, user, receiver *Pokemon, move *Move) (damag
 // Calculate the accuracy of a move, accounting for weather/evasion/held items/etc.
 func CalcAccuracy(weather Weather, user, receiver *Pokemon, move *Move) uint {
 	evasion := receiver.Evasion()
-	accuracy := move.Accuracy() * (user.Accuracy() / 100) * (evasion / 100)
+	accuracy := (move.Accuracy() * user.Accuracy() * evasion) / 10000
```
Comment (carpenterd777) [inline calc.go:87]:
```suggestion
	accuracy := (move.Accuracy() * user.Accuracy() * evasion) / (100 * 100) // multiply by 100 because the user's accuracy and evasion are out of 100
```

**Review by carpenterd777 — APPROVED** [review]

File: calc.go (hunk 1 above)
Comment (carpenterd777) [reply calc.go:87]: I meant to ask for changes but uh yanno

**Review by carpenterd777 — CHANGES_REQUESTED** [review]
a

**Review by carpenterd777 — APPROVED** [review]
