### PR TITLE
fix get opponents

### LINKED ISSUE #72: GetOpponents returns incorrect results
## Current Behavior
`GetOpponents` returns the same results as `GetAllies`

## Expected Behavior
`GetAllies` should return friendly targets.
`GetOpponents` should return enemy targets.

**Additional context**

### PR DESCRIPTION
**Pull request by dyc3**
- fix GetOpponents, fixes #72
- improve GetAllies and GetOpponents tests

### CODE REVIEW

File: battle.go [hunk 1]
```diff
@@ -65,7 +65,7 @@ func (b *Battle) GetOpponents(p *party) []target {
 	opponents := make([]target, 0)
 	targets := b.GetTargets()
 	for _, target := range targets {
-		if target.Team == p.team {
+		if target.Team != p.team {
```
Comment (adapap) [inline battle.go:68]: Woops :L

**Review by adapap — APPROVED** [review]
